spring.application.name=school-backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jpa.hibernate.ddl-auto: validate
jpa.show-sql=true
jpa.properties.hibernate.format_sql=true

server.port=8080