spring.application.name=school-backend
spring.datasource.url=jdbc:mysql://localhost:3306/school_backend
spring.datasource.username=root
spring.datasource.password=

jpa.hibernate.ddl-auto: validate
jpa.show-sql=true
jpa.properties.hibernate.format_sql=true

server.port=8080